[package]
name = "keyboard_spammer_v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal-clipboard = "0.3.1"
enigo = "0.0.14"
dotenv = "0.15.0"
rand = "0.8.3"